-- MySQL Script generated by MySQL Workbench
-- Fri 16 Dec 2016 06:22:58 PM UTC
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hadoop_metrics 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hadoop_metrics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hadoop_metrics` DEFAULT CHARACTER SET utf8 ;
USE `hadoop_metrics` ;

-- -----------------------------------------------------
-- Table `hadoop_metrics`.`rpc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`rpc` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`host` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `host` VARCHAR(28), 
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`rpc` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `call_queue_length` BIGINT NULL,
  `received_bytes` BIGINT NULL,
  `rpc_authorization_successes` BIGINT NULL,
  `rpc_client_backoff` BIGINT NULL,
  `rpc_authentication_successes` BIGINT NULL,
  `rpc_queue_time_avg_time` FLOAT NULL,
  `rpc_authentication_failures` BIGINT NULL,
  `rpc_processing_time_avg_time` FLOAT NULL,
  `timestamp` DATETIME NULL,
  `sent_bytes` BIGINT NULL,
  `rpc_authorization_failures` BIGINT NULL,
  `num_open_connections` BIGINT NULL,
  `rpc_queue_time_num_ops` BIGINT NULL,
  `rpc_processing_time_num_ops` BIGINT NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`ugi_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`ugi_metrics` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`ugi_metrics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `get_groups_num_ops` BIGINT NULL,
  `login_failure_avg_time` DOUBLE NULL,
  `login_failure_num_ops` BIGINT NULL,
  `get_groups_avg_time` DOUBLE NULL,
  `login_success_num_ops` BIGINT NULL,
  `login_success_avg_time` DOUBLE NULL,
  `timestamp` DATETIME NULL,
  `host_fk` BIGINT NULL,
  `type_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`rpc_detailed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`rpc_detailed` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`rpc_detailed` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `renew_lease_avg_time` DOUBLE NULL,
  `fsync_num_ops` BIGINT NULL,
  `fsync_avg_time` DOUBLE NULL,
  `create_avg_time` DOUBLE NULL,
  `get_block_locations_num_ops` BIGINT NULL,
  `delete_avg_time` DOUBLE NULL,
  `set_safe_mode_avg_time` DOUBLE NULL,
  `get_file_info_avg_time` DOUBLE NULL,
  `add_block_num_ops` BIGINT NULL,
  `get_server_defaults_avg_time` DOUBLE NULL,
  `create_num_ops` BIGINT NULL,
  `add_block_avg_time` DOUBLE NULL,
  `delete_num_ops` BIGINT NULL,
  `get_block_locations_avg_time` DOUBLE NULL,
  `complete_avg_time` DOUBLE NULL,
  `rename_avg_time` DOUBLE NULL,
  `mkdirs_avg_time` DOUBLE NULL,
  `mkdirs_num_ops` BIGINT NULL,
  `rename_num_ops` BIGINT NULL,
  `get_listing_num_ops` BIGINT NOT NULL,
  `complete_num_ops` BIGINT NULL,
  `set_safe_mode_num_ops` BIGINT NULL,
  `get_file_info_num_ops` BIGINT NULL,
  `get_server_defaults_num_ops` BIGINT NULL,
  `renew_lease_num_ops` BIGINT NULL,
  `get_listing_avg_time` DOUBLE NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`, `get_listing_num_ops`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`jvm_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`jvm_metrics` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`jvm_metrics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `log_error` BIGINT NULL,
  `threads_terminated` BIGINT NULL,
  `gc_account` BIGINT NULL,
  `log_fatal` BIGINT NULL,
  `gc_count_ps_mark_sweep` BIGINT NULL,
  `gc_time_millis` BIGINT NULL,
  `log_warn` BIGINT NULL,
  `gc_count_ps_scavenge` BIGINT NULL,
  `threads_blocked` BIGINT NULL,
  `mem_heap_committed_m` DOUBLE NULL,
  `mem_non_heap_used_m` DOUBLE NULL,
  `threads_runnable` BIGINT NULL,
  `gc_time_millis_ps_scavenge` BIGINT NULL,
  `mem_non_heap_committed_m` DOUBLE NULL,
  `gc_time_millis_ps_mark_sweep` BIGINT NULL,
  `mem_heap_max_m` DOUBLE NULL,
  `log_info` BIGINT NULL,
  `threads_new` BIGINT NULL,
  `mem_heap_used_m` DOUBLE NULL,
  `threads_waiting` BIGINT NULL,
  `mem_non_heap_max_m` DOUBLE NULL,
  `mem_max_m` DOUBLE NULL,
  `threads_timed_waiting` BIGINT NULL,
  `timestamp` DATETIME NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`metrics_system`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`metrics_system` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`metrics_system` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `num_all_sources` BIGINT NULL,
  `sink_logstash_num_ops` BIGINT NULL,
  `publish_num_ops` BIGINT NULL,
  `sink_logstash_q_size` BIGINT NULL,
  `num_active_sources` BIGINT NULL,
  `publish_avg_time` DOUBLE NULL,
  `timestamp` DATETIME NULL,
  `sink_logstash_avg_time` DOUBLE NULL,
  `sink_logstash_dropped` BIGINT NULL,
  `snapshot_avg_time` DOUBLE NULL,
  `num_active_sink` BIGINT NULL,
  `dropped_pub_all` BIGINT NULL,
  `snapshot_num_ops` BIGINT NULL,
  `num_all_sinks` BIGINT NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`node_manager_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`node_manager_metrics` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`node_manager_metrics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `allocated_containers` BIGINT NULL,
  `allocated_gb` BIGINT NULL,
  `containers_launched` BIGINT NULL,
  `available_v_cores` BIGINT NULL,
  `containers_running` BIGINT NULL,
  `timestamp` DATETIME NULL,
  `available_gb` BIGINT NULL,
  `containers_killed` BIGINT NULL,
  `containers_initing` BIGINT NULL,
  `containers_failed` BIGINT NULL,
  `container_launch_duration_num_ops` BIGINT NULL,
  `containers_completed` BIGINT NULL,
  `allocated_v_cores` BIGINT NULL,
  `container_launch_duration_avg_time` DOUBLE NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`shuffle_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`shuffle_metrics` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`shuffle_metrics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `shuffle_output_bytes` BIGINT NULL,
  `shuffle_connections` BIGINT NULL,
  `shuffle_outputs_ok` BIGINT NULL,
  `shuffle_outputs_failed` BIGINT NULL,
  `timestamp` DATETIME NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`queue_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`queue_metrics` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`queue_metrics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `apps_failed` BIGINT NULL,
  `apps_completed` BIGINT NULL,
  `min_share_mb` BIGINT NULL,
  `apps_killed` BIGINT NULL,
  `active_applications` BIGINT NULL,
  `running_300` BIGINT NULL,
  `steady_fair_share_mb` BIGINT NULL,
  `pending_mb` BIGINT NULL,
  `running_60` BIGINT NULL,
  `reserved_mb` BIGINT NULL,
  `pending_containers` BIGINT NULL,
  `available_mb` BIGINT NULL,
  `timestamp` DATETIME NULL,
  `allocated_mb` BIGINT NULL,
  `allocated_containers` BIGINT NULL,
  `max_share_v_cores` BIGINT NULL,
  `running_0` BIGINT NULL,
  `running_1440` BIGINT NULL,
  `active_users` BIGINT NULL,
  `pending_v_cores` BIGINT NULL,
  `steady_fair_share_v_cores` BIGINT NULL,
  `available_v_cores` BIGINT NULL,
  `max_share_mb` BIGINT NULL,
  `aafca_delay_num_ops` BIGINT NULL,
  `apps_running` BIGINT NULL,
  `agg_containers_released` BIGINT NULL,
  `min_share_v_cores` BIGINT NULL,
  `aafca_delay_avg_time` DOUBLE NULL,
  `reserved_v_cores` BIGINT NULL,
  `reserved_containers` BIGINT NULL,
  `apps_submitted` BIGINT NULL,
  `apps_pending` BIGINT NULL,
  `allocated_v_cores` BIGINT NULL,
  `aggregate_containers_allocated` BIGINT NULL,
  `fair_share_mb` BIGINT NULL,
  `fair_share_v_cores` BIGINT NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`fs_op_durations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`fs_op_durations` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`fs_op_durations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `update_call_i_max_time` DOUBLE NULL,
  `node_update_call_min_time` DOUBLE NULL,
  `update_call_max_time` DOUBLE NULL,
  `update_thread_run_i_min_time` DOUBLE NULL,
  `continuous_scheduling_run_i_min_time` DOUBLE NULL,
  `continuous_scheduling_run_i_num_ops` BIGINT NULL,
  `update_call_min_time` DOUBLE NULL,
  `update_thread_run_min_time` DOUBLE NULL,
  `preempt_call_avg_time` DOUBLE NULL,
  `preempt_call_min_time` DOUBLE NULL,
  `update_thread_run_stdev_time` DOUBLE NULL,
  `update_call_avg_time` DOUBLE NULL,
  `node_update_call_i_min_time` DOUBLE NULL,
  `continuous_scheduling_run_num_ops` BIGINT NULL,
  `continuous_scheduling_run_i_max_time` DOUBLE NULL,
  `node_update_call_num_ops` BIGINT NULL,
  `update_call_i_num_ops` BIGINT NULL,
  `node_update_call_avg_time` DOUBLE NULL,
  `preempt_call_i_min_time` DOUBLE NULL,
  `preempt_call_num_ops` BIGINT NULL,
  `node_update_call_i_max_time` DOUBLE NULL,
  `update_thread_run_i_max_time` DOUBLE NULL,
  `preempt_call_max_time` DOUBLE NULL,
  `update_thread_run_max_time` DOUBLE NULL,
  `update_thread_run_avg_time` DOUBLE NULL,
  `node_update_call_stdev_time` DOUBLE NULL,
  `update_thread_run_num_ops` BIGINT NULL,
  `update_call_stdev_time` DOUBLE NULL,
  `preempt_call_i_max_time` DOUBLE NULL,
  `node_update_call_i_num_ops` BIGINT NULL,
  `continuous_scheduling_run_max_time` DOUBLE NULL,
  `update_thread_run_i_num_ops` BIGINT NULL,
  `preempt_call_stdev_time` DOUBLE NULL,
  `timestamp` DATETIME NULL,
  `update_call_i_min_time` DOUBLE NULL,
  `update_call_num_ops` BIGINT NULL,
  `continuous_scheduling_run_min_time` DOUBLE NULL,
  `continuous_scheduling_run_avg_time` DOUBLE NULL,
  `node_update_call_max_time` DOUBLE NULL,
  `continuous_scheduling_run_stdev_time` DOUBLE NULL,
  `preempt_call_i_num_ops` BIGINT NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`cluster_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`cluster_metrics` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`cluster_metrics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `num_unhealthy_nms` BIGINT NULL,
  `am_register_delay_num_ops` BIGINT NULL,
  `num_decommissioned_nms` BIGINT NULL,
  `num_active_nms` BIGINT NULL,
  `am_launch_delay_avg_time` DOUBLE NULL,
  `timestamp` DATETIME NULL,
  `num_rebooted_nms` BIGINT NULL,
  `am_launch_delay_num_ops` BIGINT NULL,
  `am_register_delay_avg_time` DOUBLE NULL,
  `num_lost_nms` BIGINT NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`data_node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`data_node` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`data_node` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ram_disk_blocks_eviction_window_ms_avg_time` DOUBLE NULL,
  `write_block_op_avg_time` DOUBLE NULL,
  `blocks_removed` BIGINT NULL,
  `remote_bytes_written` BIGINT NULL,
  `block_checksum_op_num_ops` BIGINT NULL,
  `heartbeats_avg_time` DOUBLE NULL,
  `fsync_count` BIGINT NULL,
  `read_block_op_avg_time` DOUBLE NULL,
  `packet_ack_round_trip_time_nanos_avg_time` DOUBLE NULL,
  `send_data_packet_transfer_nanos_num_ops` BIGINT NULL,
  `block_checksum_op_avg_time` DOUBLE NULL,
  `writes_from_local_client` BIGINT NULL,
  `blocks_uncached` BIGINT NULL,
  `ram_disk_blocks_lazy_persist_window_ms_avg_time` DOUBLE NULL,
  `blocks_replicated` BIGINT NULL,
  `packet_ack_round_trip_time_nanos_num_ops` BIGINT NULL,
  `copy_block_op_avg_time` DOUBLE NULL,
  `blocks_read` BIGINT NULL,
  `ram_disk_blocks_read_hits` BIGINT NULL,
  `timestamp` DATETIME NULL,
  `cache_reports_avg_time` DOUBLE NULL,
  `blocks_verified` BIGINT NULL,
  `replace_block_op_num_ops` BIGINT NULL,
  `heartbeats_num_ops` BIGINT NULL,
  `writes_from_remote_client` BIGINT NULL,
  `reads_from_remote_client` BIGINT NOT NULL,
  `block_reports_avg_time` DOUBLE NULL,
  `ram_disk_blocks_eviction_window_ms_num_ops` BIGINT NULL,
  `fsync_nanos_num_ops` BIGINT NULL,
  `replace_block_op_avg_time` DOUBLE NULL,
  `total_write_time` DOUBLE NULL,
  `reads_from_local_client` BIGINT NULL,
  `ram_disk_bytes_write` BIGINT NULL,
  `volume_failures` BIGINT NULL,
  `write_block_op_num_ops` BIGINT NULL,
  `blocks_written` BIGINT NULL,
  `ram_disk_blocks_deleted_before_lazy_persisted` BIGINT NULL,
  `copy_block_op_num_ops` BIGINT NULL,
  `total_read_time` DOUBLE NULL,
  `ram_disk_blocks_write_fallback` BIGINT NULL,
  `flush_nanos_num_ops` BIGINT NULL,
  `blocks_cached` BIGINT NULL,
  `blocks_get_local_path_info` BIGINT NULL,
  `cache_reports_num_ops` BIGINT NULL,
  `send_data_packet_transfer_nanos_avg_time` DOUBLE NULL,
  `bytes_read` BIGINT NULL,
  `ram_disk_blocks_write` BIGINT NULL,
  `incremental_block_reports_num_ops` BIGINT NULL,
  `flush_nanos_avg_time` DOUBLE NULL,
  `ram_disk_blocks_evicted` BIGINT NULL,
  `datanode_network_errors` BIGINT NULL,
  `send_data_packet_blocked_on_network_nanos_num_opsd` BIGINT NULL,
  `ram_disk_blocks_lazy_persist_window_ms_num_ops` BIGINT NULL,
  `send_data_packet_blocked_on_network_nanos_avg_time` DOUBLE NULL,
  `ram_disk_bytes_lazy_persisted` BIGINT NULL,
  `ram_disk_blocks_lazy_persisted` BIGINT NULL,
  `read_block_op_num_ops` BIGINT NULL,
  `block_verification_failures` BIGINT NULL,
  `remote_bytes_read` BIGINT NULL,
  `block_reports_num_ops` BIGINT NULL,
  `fsync_nanos_avg_time` DOUBLE NULL,
  `bytes_written` BIGINT NULL,
  `ram_disk_blocks_evicted_without_read` BIGINT NULL,
  `incremental_block_reports_avg_time` DOUBLE NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`, `reads_from_remote_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`name_node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`name_node` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`name_node` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `list_snapshot_table_dir_ops` BIGINT NULL,
  `put_image_num_ops` BIGINT NULL,
  `allow_snapshot_ops` BIGINT NULL,
  `transactions_num_ops` BIGINT NULL,
  `cache_report_num_ops` BIGINT NULL,
  `sync_savg_time` DOUBLE NULL,
  `get_additional_datanode_ops` BIGINT NULL,
  `rename_snapshot_ops` BIGINT NULL,
  `create_file_ops` BIGINT NULL,
  `get_listing_ops` BIGINT NULL,
  `syncs_num_ops` BIGINT NULL,
  `get_block_locations` BIGINT NULL,
  `files_in_get_listing_ops` BIGINT NULL,
  `storage_block_report_ops` BIGINT NULL,
  `safe_mode_time` BIGINT NULL,
  `files_created` BIGINT NULL,
  `delete_file_ops` BIGINT NULL,
  `get_edit_num_ops` BIGINT NULL,
  `cache_report_avg_time` DOUBLE NULL,
  `delete_snapshot_ops` BIGINT NULL,
  `add_block_ops` BIGINT NULL,
  `files_renamed` BIGINT NULL,
  `get_image_num_ops` BIGINT NULL,
  `transactions_batched_in_sync` BIGINT NULL,
  `block_report_avg_time` DOUBLE NULL,
  `create_snapshot_ops` BIGINT NULL,
  `get_edit_avg_time` BIGINT NULL,
  `file_info_ops` BIGINT NULL,
  `block_report_num_ops` BIGINT NULL,
  `get_image_avg_time` DOUBLE NULL,
  `put_image_avg_time` DOUBLE NULL,
  `timestamp` DATETIME NULL,
  `disallow_snapshot_ops` BIGINT NULL,
  `block_received_and_deleted_ops` BIGINT NULL,
  `transactions_avg_time` DOUBLE NULL,
  `create_symlink_ops` BIGINT NULL,
  `total_file_ops` BIGINT NULL,
  `files_deleted` BIGINT NULL,
  `get_link_target_ops` BIGINT NULL,
  `fs_image_load_time` BIGINT NULL,
  `files_appended` BIGINT NULL,
  `snapshot_diff_report_ops` BIGINT NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`namenode_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`namenode_metrics` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`namenode_metrics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `set_times_num_ops` BIGINT NULL,
  `renew_lease_avg_time` DOUBLE NULL,
  `fsync_num_ops` BIGINT NULL,
  `fsync_avg_time` DOUBLE NULL,
  `create_avg_time` DOUBLE NULL,
  `get_block_locations_num_ops` BIGINT NULL,
  `delete_avg_time` DOUBLE NULL,
  `set_safe_mode_avg_time` DOUBLE NULL,
  `get_file_info_avg_time` DOUBLE NULL,
  `add_block_num_ops` BIGINT NULL,
  `get_server_defaults_avg_time` DOUBLE NULL,
  `create_num_ops` BIGINT NULL,
  `add_block_avg_time` DOUBLE NULL,
  `delete_num_ops` BIGINT NULL,
  `get_block_locations_avg_time` DOUBLE NULL,
  `complete_avg_time` DOUBLE NULL,
  `settimes_avg_time` DOUBLE NULL,
  `rename_avg_time` DOUBLE NULL,
  `mkdirs_avg_time` DOUBLE NULL,
  `mkdirs_num_ops` BIGINT NULL,
  `rename_num_ops` BIGINT NULL,
  `get_listing_num_ops` BIGINT NULL,
  `complete_num_ops` BIGINT NULL,
  `timestamp` DATETIME NULL,
  `set_safe_mode_num_ops` BIGINT NULL,
  `get_file_info_num_ops` BIGINT NULL,
  `get_server_defaults_num_ops` BIGINT NULL,
  `renew_lease_num_ops` BIGINT NULL,
  `get_listing_avg_time` DOUBLE NULL,
  `@version` BIGINT NULL,
-- `metric_type` => `namenode-metrics`,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `hadoop_metrics`.`namenode_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`namenode_metrics_more` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`namenode_metrics_more` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `blockreceivedanddeletednumops` BIGINT NULL,
  `registerdatanodenumops` BIGINT NULL,
  `blockreportavgtime` DOUBLE NULL,
  `gettransactionidnumops` BIGINT NULL,
  `versionrequestavgtime` DOUBLE NULL,
  `rolleditlognumops` BIGINT NULL,
  `blockreportnumops` BIGINT NULL,
  `registerdatanodeavgtime` DOUBLE NULL,
  `sendheartbeatavgtime` DOUBLE NULL,
  `timestamp` DATETIME NULL,
  `geteditlogmanifestavgtime` DOUBLE NULL,
  `versionrequestnumops` BIGINT NULL,
  `gettransactionidavgtime` DOUBLE NULL,
  `geteditlogmanifestnumops` BIGINT NULL,
  `sendheartbeatnumops` BIGINT NULL,
  `rolleditlogavgtime` DOUBLE NULL,
  `blockreceivedanddeletedavgtime` DOUBLE NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`resourcemanager_metrics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`resourcemanager_metrics` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`resourcemanager_metrics` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NULL,
  `nodeheartbeatavgtime` DOUBLE NULL,
  `registernodemanageravgtime` DOUBLE NULL,
  `registernodemanagernumops` BIGINT NULL,
  `nodeheartbeatnumops` BIGINT NULL,
--  `metric_type` => `resourcemanager-metrics`
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`startup_progress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`startup_progress` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`startup_progress` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `loading_edits_percent_complete` DOUBLE NULL,
  `percent_complete` DOUBLE NULL,
  `loading_edits_total` BIGINT NULL,
  `safe_mode_percent_complete` DOUBLE NULL,
  `safe_mode_elapsed_time` BIGINT NULL,
  `saving_checkpoint_percent_complete` DOUBLE NULL,
  `saving_checkpoint_count` BIGINT NULL,
  `safe_mode_count` BIGINT NULL,
  `saving_checkpoint_elapsed_time` BIGINT NULL,
  `loading_fs_image_count` BIGINT NULL,
  `loading_fs_image_percent_complete` DOUBLE NULL,
  `loading_edits_count` BIGINT NULL,
  `loading_fs_image_total` BIGINT NULL,
  `elapsed_time` BIGINT NULL,
  `loading_edits_elapsed_time` BIGINT NULL,
  `safe_mode_total` BIGINT NULL,
  `loading_fs_image_elapsed_time` BIGINT NULL,
  `saving_checkpoint_total` BIGINT NULL,
  `timestamp` DATETIME NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`fs_name_system`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`fs_name_system` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`fs_name_system` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `capacity_used` BIGINT NULL,
  `excess_blocks` BIGINT NULL,
  `pending_replication_blocks` BIGINT NULL,
  `files_total` BIGINT NULL,
  `capacity_used_non_dfs` BIGINT NULL,
  `capacity_remaining_gb` BIGINT NULL,
  `capacity_remaining` BIGINT NULL,
  `total_load` BIGINT NULL,
  `transactions_since_last_checkpoint` BIGINT NULL,
  `pending_deletion_blocks` BIGINT NULL,
  `last_checkpoint_time` BIGINT NULL,
  `block_capacity` BIGINT NULL,
  `scheduled_replication_blocks` BIGINT NULL,
  `blocks_total` BIGINT NULL,
  `capacity_total_gb` DOUBLE NULL,
  `capacity_used_gb` DOUBLE NULL,
  `expired_heartbeats` BIGINT NULL,
  `total_files` BIGINT NULL,
  `stale_data_nodes` BIGINT NULL,
  `postponed_misreplicated_blocks` BIGINT NULL,
  `transactions_since_last_log_roll` BIGINT NULL,
  `missing_blocks` BIGINT NULL,
  `pending_data_node_message_count` BIGINT NULL,
  `millis_since_last_loaded_edits` BIGINT NULL,
  `timestamp` DATETIME NULL,
  `last_written_transaction_id` BIGINT NULL,
  `snapshottable_directories` BIGINT NULL,
  `missing_repl_one_blocks` BIGINT NULL,
  `under_replicated_blocks` BIGINT NULL,
  `snapshots` BIGINT NULL,
  `capacity_total` BIGINT NULL,
  `corrupt_blocks` BIGINT NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hadoop_metrics`.`name_node_retry_cache`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hadoop_metrics`.`name_node_retry_cache` ;

CREATE TABLE IF NOT EXISTS `hadoop_metrics`.`name_node_retry_cache` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cache_hit` BIGINT NULL,
  `cache_updated` BIGINT NULL,
  `cache_cleared` BIGINT NULL,
  `timestamp` DATETIME NULL,
  `type_fk` BIGINT NULL,
  `host_fk` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
